### ISSUE TITLE
Number of countries

### ISSUE THREAD

**Issue by IanaKhitsko** [Miracle-Aligner/EuroDiffusionProblem#10]
https://github.com/Miracle-Aligner/EuroDiffusionProblem/blob/fc7d01f3b1a0ba2b574c679ccf7a9dda8a8da4d0/EuroDiffusionProblem/CoinsDiffusionUtils.cs#L27

Number of countries shall be <= 20

**Comment by Miracle-Aligner** [comment]
The number of countries stated in the first sentence of a task as far as I see:
> On January 1, 2002, twelve European countries abandoned their national currency for a new
currency, the euro.

And further:
> No matter which motif is on the coin, it can be used anywhere in the 12 Member States.
