### ISSUE TITLE
Early return

### ISSUE THREAD

**Issue by IanaKhitsko** [Miracle-Aligner/EuroDiffusionProblem#8]
https://github.com/Miracle-Aligner/EuroDiffusionProblem/blob/fc7d01f3b1a0ba2b574c679ccf7a9dda8a8da4d0/EuroDiffusionProblem/Country.cs#L76-L78

            if (amountToTransport <= 0)
                return 0;
            int transportedInGeneral = 0;

**Comment by Miracle-Aligner** [comment]
Fixed
