### ISSUE TITLE
User ternar operator? 

### ISSUE THREAD

**Issue by IanaKhitsko** [Miracle-Aligner/EuroDiffusionProblem#9]
https://github.com/Miracle-Aligner/EuroDiffusionProblem/blob/fc7d01f3b1a0ba2b574c679ccf7a9dda8a8da4d0/EuroDiffusionProblem/Country.cs#L111

Consider to use ternar operator , e.g. return (...) ? false : generalCountriesGrid[x, y];

**Comment by Miracle-Aligner** [comment]
Fixed
